// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hello.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace TestProto {
  public static partial class HelloWorldService
  {
    static readonly string __ServiceName = "HelloWorldService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::TestProto.HelloRequest> __Marshaller_HelloRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::TestProto.HelloRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::TestProto.HelloResponse> __Marshaller_HelloResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::TestProto.HelloResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::TestProto.HelloRequest, global::TestProto.HelloResponse> __Method_hello = new grpc::Method<global::TestProto.HelloRequest, global::TestProto.HelloResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "hello",
        __Marshaller_HelloRequest,
        __Marshaller_HelloResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::TestProto.HelloRequest, global::TestProto.HelloResponse> __Method_helloServer = new grpc::Method<global::TestProto.HelloRequest, global::TestProto.HelloResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "helloServer",
        __Marshaller_HelloRequest,
        __Marshaller_HelloResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::TestProto.HelloRequest, global::TestProto.HelloResponse> __Method_helloClient = new grpc::Method<global::TestProto.HelloRequest, global::TestProto.HelloResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "helloClient",
        __Marshaller_HelloRequest,
        __Marshaller_HelloResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::TestProto.HelloRequest, global::TestProto.HelloResponse> __Method_helloBoth = new grpc::Method<global::TestProto.HelloRequest, global::TestProto.HelloResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "helloBoth",
        __Marshaller_HelloRequest,
        __Marshaller_HelloResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::TestProto.HelloReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloWorldService</summary>
    [grpc::BindServiceMethod(typeof(HelloWorldService), "BindService")]
    public abstract partial class HelloWorldServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::TestProto.HelloResponse> hello(global::TestProto.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task helloServer(global::TestProto.HelloRequest request, grpc::IServerStreamWriter<global::TestProto.HelloResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::TestProto.HelloResponse> helloClient(grpc::IAsyncStreamReader<global::TestProto.HelloRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task helloBoth(grpc::IAsyncStreamReader<global::TestProto.HelloRequest> requestStream, grpc::IServerStreamWriter<global::TestProto.HelloResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HelloWorldService</summary>
    public partial class HelloWorldServiceClient : grpc::ClientBase<HelloWorldServiceClient>
    {
      /// <summary>Creates a new client for HelloWorldService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public HelloWorldServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HelloWorldService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public HelloWorldServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected HelloWorldServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected HelloWorldServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::TestProto.HelloResponse hello(global::TestProto.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return hello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::TestProto.HelloResponse hello(global::TestProto.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_hello, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::TestProto.HelloResponse> helloAsync(global::TestProto.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return helloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::TestProto.HelloResponse> helloAsync(global::TestProto.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_hello, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::TestProto.HelloResponse> helloServer(global::TestProto.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return helloServer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::TestProto.HelloResponse> helloServer(global::TestProto.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_helloServer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::TestProto.HelloRequest, global::TestProto.HelloResponse> helloClient(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return helloClient(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::TestProto.HelloRequest, global::TestProto.HelloResponse> helloClient(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_helloClient, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::TestProto.HelloRequest, global::TestProto.HelloResponse> helloBoth(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return helloBoth(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::TestProto.HelloRequest, global::TestProto.HelloResponse> helloBoth(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_helloBoth, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override HelloWorldServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloWorldServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(HelloWorldServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_hello, serviceImpl.hello)
          .AddMethod(__Method_helloServer, serviceImpl.helloServer)
          .AddMethod(__Method_helloClient, serviceImpl.helloClient)
          .AddMethod(__Method_helloBoth, serviceImpl.helloBoth).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, HelloWorldServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_hello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::TestProto.HelloRequest, global::TestProto.HelloResponse>(serviceImpl.hello));
      serviceBinder.AddMethod(__Method_helloServer, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::TestProto.HelloRequest, global::TestProto.HelloResponse>(serviceImpl.helloServer));
      serviceBinder.AddMethod(__Method_helloClient, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::TestProto.HelloRequest, global::TestProto.HelloResponse>(serviceImpl.helloClient));
      serviceBinder.AddMethod(__Method_helloBoth, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::TestProto.HelloRequest, global::TestProto.HelloResponse>(serviceImpl.helloBoth));
    }

  }
}
#endregion
